title: Devman Blog
description: ""
baseurl: ""
url: "https://devman-kr.github.io"
lang: ko

author:
  name: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Multilingual settings
languages: ["ko", "en"]
default_lang: "ko"

# Minima settings
minima:
  skin: dark
  date_format: "%Y-%m-%d"
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/devman-kr"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
